const express= require("express");
const app= express();
const cors= require("cors");

const {comp, add}= require("./zodVerify.js");
const { todoObject } = require("./database.js");

app.use(express.json());
app.use(cors());

app.post("/addTodo", function(req, res){
    const input= req.body;

    const verify= add.safeParse(input);
    if(!verify.success){
        res.status(422).send("Invalid Input");
        return;
    }

    const newTodo= new todoObject({
        title: input.title,
        description: input.description,
        id: false
    })
    newTodo.save().then(function (){
        res.status(200).send("To Do Added");
    })
})

app.get("/listTodos", function(req, res){
    todoObject.find({})
        .then(function(resp){
            res.status(200).json(resp);
        })
})

app.put("/completed", function (req, res){
    const uniqueId= req.body.uniqueId;
    //unique id is the one generated by mongodb, i.e. _id
    //id is the boolean type we'd update in the database
    const verifyInput= add.safeParse(uniqueId);
    if(!verifyInput.success){
        res.status(422).send("Invalid Id")
        return;
    }
    todoObject.update({_id: uniqueId}, {id: true})
        .then(function(){
            res.status(200).send("Marked completed")
        })
})


app.listen(3000);